### ISSUE TITLE
Read and summarise this article about open source etiquettes

### ISSUE THREAD

**Issue by umeshSinghVerma** [iiitl/git-practice-weekend-24#1]
Read https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette and write a summary in 60-120 words. You may choose to highlight any specific portions that feel especially relevant, or write a summary of the entire document in general. For bonus points, mention and cite additional points that aren't mentioned in the document, but should be.

**Comment by vishalparida** [comment]
The article outlines key etiquettes and essential guidelines for newcomers to open source projects (OSPs). It stresses understanding personal motivations for contributing and maintaining kindness and respect towards fellow contributors. Emphasis is placed on effective contributions, adherence to project guidelines, and seeking help when needed. Contributors are reminded to respect project moderators' decisions and to maintain patience and timeliness in their interactions. The article promotes a collaborative and supportive environment while urging contributors to communicate effectively and avoid unnecessary noise. Overall, it serves as a valuable guide for navigating OSPs with professionalism by fostering a culture of respect, collaboration, and effective communication.
Key Takeaways (which I will definitely keep in mind while contributing):
1) Adherence to Code of Conduct: Following the OSP's code of conduct to maintain a comfortable and inclusive environment, reporting any behavior that violates these guidelines.
2) Respect for Decision-Making: Respecting decisions made by moderators or core contributors.
3) Patience and Timeliness: Being patient when awaiting responses or reviews.
4) Mutual Courtesy: Extending the same courtesy to others as you expect from them, communicating if unable to fulfill obligations and seeking assistance when necessary.

**Comment by gauravghodinde** [comment]
This article is about etiquette for contributing to open source projects (OSPs). It covers things like how to be respectful, how to choose good contributions to make, and how to find the information you need. Some of the important points are:

Be polite and kind to other contributors.
Choose contributions that are helpful to the project.
Read the project's documentation before asking questions.
Be patient when waiting for responses from other contributors.

**Comment by rootCircle** [comment]
Looks great! @vishalparida @gauravghodinde please make a PR with the summary in a text/md file with the summary! Don't put the summary here

**Comment by akhilender-bongirwar** [comment]
Do not use AI tools for summarizing this article!! Try reading the article on your own and write few points according to your understanding.
