### ISSUE TITLE
Follow the instruction given in REBASE.md and create a PR

### ISSUE THREAD

**Issue by umeshSinghVerma** [iiitl/git-practice-weekend-24#8]
Follow the instructions in https://github.com/iiitl/git-practice-weekend-24/blob/master/REBASE.md and create a PR as described.

**Comment by blunterdecosta123** [comment]
Hello @umeshSinghVerma,

I've been working on a pull request that involves rebasing commits in git. Given my involvement in the changes and my familiarity with the codebase, I believe I am well-positioned to handle the review and further iterations on this pull request.

**Comment by rootCircle** [comment]
@blunterdecosta123 please complete all the earlier issues(#1 is optional) before this one, to get this assigned! Ping me when it's done!

**Comment by blunterdecosta123** [comment]
I have completed almost all issues before and want you to assign me this pr that involves rebasing commits in git.I have enough familiarity to work on this code.

**Comment by rootCircle** [comment]
@blunterdecosta123 sure go ahead! Ping us if you need any help!

**Comment by sulfur05** [comment]
@rootCircle please assign me this issue, I have the solution for it ready with me

**Comment by akhilender-bongirwar** [comment]
@sulfur05 assigned.
